version: 3

tasks:
  generate:
    cmds:
      - git -C /home/sheepman/packages pull
      - python main.py /home/sheepman/packages

  deploy:
    cmds:
      - rsync -avz deploy/* sheepman@packages.getsol.us:/srv/shared/sheepman/update-dashboard

  default:
    cmds:
      - task: generate
      - task: deploy
