version: 3

tasks:
  generate:
    cmds:
      - git -C /home/sheepman/packages pull
      - python main.py /home/sheepman/packages

  deploy:
      - rsync -avz deploy/* /srv/packaging-dashboard

  default:
    cmds:
      - task: generate
      - task: deploy
